# npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvmCKAGES="${HOME}/.npm-packages"

# manpages
unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# dotfiles
PATH="$PATH:$HOME/git/me/bag-of-tricks/bin"
PATH="$PATH:$HOME/git/me/bag-of-tricks/.cache/git-semantic-commits"

export PATH
export EDITOR='vim'
