# npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvmCKAGES="${HOME}/.npm-packages"

# manpages
unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# dotfiles
PATH="$PATH:$HOME/git/me/bag-of-tricks/bin"
PATH="$PATH:$HOME/git/me/bag-of-tricks/.cache/git-semantic-commits"

# git aliases

# Lists the last 10 branches you worked on
# Run `git lastworks`
# https://gist.github.com/AvnerCohen/a25a69df4e13f469c4ee
git config --global alias.lastworks "for-each-ref --count=10 --sort=-committerdate refs/heads/"

export PATH
export EDITOR='vim'
