#!/bin/bash

terminal-notifier -title "Test" -message "🍅 Pomodoro complete" -sound "glass"

$HOME/git/oss/slack_status_updater/slack_status.sh none
$HOME/git/oss/slack_status_updater/awayback.sh back
open -a Slack
