#!/bin/bash

set -e

logAnnounce () {
  echo "🚦 $@"
}

logSuccess () {
  echo "✅ $@"
}

logNoop () {
  echo "👍 $@"
}

maybeInstallBrew () {
  if [ -z "$(command -v brew)" ]; then
    logAnnounce "installing homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    logSuccess "successfully installed homebrew"
  else
    logNoop "homebrew already installed"
  fi
}

maybeInstallNvm () {
  if [ ! -d "$HOME/.nvm" ]; then
    logAnnounce "installing nvm..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    logSuccess "successfully installed nvm"
  else
    logNoop "nvm already installed"
  fi
}

maybeInstallOhMyZsh () {
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    logAnnounce "installing oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    logSuccess "successfully installed oh-my-zsh"
  else
    logNoop "oh-my-zsh already installed"
  fi

}

maybeSetShellToZsh () {
  if [ "$(basename $SHELL)" != "zsh" ]; then
    logAnnounce "setting shell to zsh" 
    chsh -s "$(which zsh)"
    logSuccess "successfully set shell to zsh"
  else
    logNoop "shell already set to zsh"
  fi
}

maybeInstallPathogen () {
  if [ ! -f "$HOME/autoload/pathogen.vim" ]; then
    logAnnounce "installing pathogen"
    mkdir -p $HOME/.vim/autoload $HOME/.vim/bundle && \
    curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    logSuccess "successfully installed pathogen"
  else
    logNoop "pathogen already installed"
  fi
}

installOrUpdateCocExtensions () {
  logAnnounce "installing / updating coc extensions"
  cd $HOME/.config/coc/extensions && npm install && cd $HOME
  logSuccess "coc extensions up-to-date"
}

maybeSetUpDropboxSymlinks () {
  if [ ! -d $HOME/notes ]; then
    logAnnounce "setting up dropbox symlinks"
    mkdir -p ~/Dropbox/notes
    ln -sf $HOME/Dropbox/notes $HOME/notes
    logSuccess "successfully set up Dropbox symlinks"
  else
    logNoop "dropbox symlinks already setup"
  fi
}

maybeInstallTpm () {
  if [ ! -d $HOME/.tmux/plugins/tpm ]; then
    logAnnounce "installing tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    logSuccess "successfully installed tpm"
  else
    logNoop "tpm already installed"
  fi
}

#
# Bootstraps a machine. All the operations here should be idempotent.
#
bootstrap () {
  maybeInstallBrew

  # Must be run after brew but before zsh since it may install zsh 
  brew bundle install

  maybeSetShellToZsh
  maybeInstallOhMyZsh
  maybeInstallNvm
  maybeInstallPathogen

  # In case it hasn't yet been sourced.
  source ~/.zshrc

  # Sets up vim/nvim plugins via pathogen.
  pgen install

  installOrUpdateCocExtensions
}

bootstrap
