echo "Loading remote bash configuration"
echo "..."

export DOTFILES_PATH="$HOME/git/me/bag-of-tricks"

# npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvmCKAGES="${HOME}/.npm-packages"

# manpages
unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# dotfiles
PATH="$PATH:$DOTFILES_PATH/bin"

# node_modules
PATH="$PATH:$DOTFILES_PATH/node_modules/.bin"

# cargo
PATH="$PATH:$HOME/.cargo/bin"

# todo.txt
export TODOTXT_CFG_FILE=$DOTFILES_PATH/rc/todo.cfg

export PATH
export EDITOR='vim'

LOCAL_CONFIG_FILE="/Users/$USER/.localrc"

if [ -f "$LOCAL_CONFIG_FILE" ]; then
  echo "Loading local bash configuration"
  echo '...'
  source $LOCAL_CONFIG_FILE
  echo "Successfully loaded local bash configuration"
  echo '...'
else
  echo "Warning - No local bash configuration found. You may be missing important environment settings."
  echo "Please ensure the existence of /Users/$USER/.localrc"
  echo "..."
fi

echo "Successfully loaded remote bash configuration"
echo "..."
