execute pathogen#infect()
syntax on
" Enable filetype plugin detection under ~/.vim/ftplugin
" https://www.gilesorr.com/blog/vim-ftplugin.html
filetype plugin indent on

" # .vimrc

" :)

" ------------------------------
" ## Settings
" ------------------------------

" Note that colors are no longer configured here as I'm preferring to use
" colors consistent with my terminal theme configured in alacritty.yaml.
" @see https://jeffkreeftmeijer.com/vim-16-color/

" Use zsh as shell inside vim
set shell=/bin/zsh

" Line numbers
set relativenumber

" Tab size
set tabstop=2
set shiftwidth=2
set expandtab

" Open vertical splits to the right, not left
set splitright

let mapleader="\<space>"

" Specify spellcheck dict location
" @see https://www.ostechnix.com/use-spell-check-feature-vim-text-editor/
set spellfile=~/.vim/spell/en.utf-8.add

" Enable spell in git commits
" @see https://stackoverflow.com/a/19485184
autocmd FileType gitcommit setlocal spell

" Highlight line in insert mode
" https://stackoverflow.com/a/6489348/2423549
" :autocmd InsertEnter * set cul
" :autocmd InsertLeave * set nocul

" Change cursor shape when switching between insert / normal mode
" https://stackoverflow.com/a/30199177/2423549
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Modify behaviors for opening windows in netrw - currently set
" to open in same window.
" @see https://groups.google.com/d/msg/vim_use/Gb_YeadW5FE/5wptj3orcSsJ
" @see https://vi.stackexchange.com/a/19924 (Previous settings)
let g:netrw_browse_split = 0

" Assume use of JSONC format for syntax highlighting
" @see https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file
autocmd FileType json syntax match Comment +\/\/.\+$+

" Make double-<Esc> clear search highlights
" @see https://stackoverflow.com/a/19877212
nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<CR><Esc>

" ------------------------------
" ## Mappings
" ------------------------------

" Switch between buffers with Ctrl
nnoremap <C-l> :bn<Cr> 
nnoremap <C-h> :bp<Cr> 

" Open terminal in vertical split
nnoremap <C-j> :vs\|:te<Cr>

" " Use escape in terminal mode because it's simpler
" tnoremap <Esc> <C-\><C-n>

" ------------------------------
" ## Plugins
" ------------------------------

" ### fzf.vim

" Re-map fzf to Ctrl-p with MRU bindings
nnoremap <C-p> :FilesMru<Cr>

" Respect gitignore / prefer ag
" @see https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

" Make :Ag not match file names, only the file content
" @see https://github.com/junegunn/fzf.vim/issues/346
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)

" ### vim-prettier

" Enable vim-prettier to run (async) in files without requiring the "@format" doc tag
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync

" ### CamelCaseMotion.vim

" Use default mappings
" @see https://github.com/bkad/CamelCaseMotion
let g:camelcasemotion_key = '<leader>'


" ### vim-fugitive

" Prefer Vertical split for Gdiff (not fugitive-specific)
" @see https://github.com/tpope/vim-fugitive/issues/510
" @see https://github.com/thoughtbot/dotfiles/issues/655#issuecomment-605019271
if &diff
    set diffopt-=internal
    set diffopt+=vertical
endif

" ### async-run / async-tasks
" @see https://github.com/skywind3000/asynctasks.vim#get-started

" Open quickfix window automatically
let g:asyncrun_open = 6

" Open an internal terminal
let g:asynctasks_term_pos = 'right'

" ### VSCode-like settings

" Shortcut to pop Task list
nnoremap <C-r><C-t> :CocList tasks<Cr>


" Support gx inside vim terminal buffers

function! Open(url)
  silent execute '!open ' . a:url
  redraw!
endfunction

autocmd BufEnter term://* nnoremap <buffer> gx viW"xy \| :call Open(@x)<CR>
