execute pathogen#infect()

" # .vimrc

" :)

" ------------------------------
" ## Settings
" ------------------------------

syntax on
colorscheme codeschool

" Enable filetype plugin detection under ~/.vim/ftplugin
" https://www.gilesorr.com/blog/vim-ftplugin.html
filetype plugin indent on

" Line numbers
set number

" Tab size
set tabstop=2
set shiftwidth=2
set expandtab

" Open vertical splits to the right, not left
set splitright

let maplocalleader="\<space>"

" Highlight line in insert mode
" https://stackoverflow.com/a/6489348/2423549
" :autocmd InsertEnter * set cul
" :autocmd InsertLeave * set nocul

" Change cursor shape when switching between insert / normal mode
" https://stackoverflow.com/a/30199177/2423549
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" ------------------------------
" ## Plugins
" ------------------------------

" ### CtrlP

" - https://github.com/ctrlpvim/ctrlp.vim#basic-options
" - http://tmr08c.github.io/vim/2015/09/19/making-nerdtree-and-ctrlp-play-nice.html
" - https://superuser.com/questions/1141994/autorefresh-nerdtree

" CtrlP search ignore respects .gitignore
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" Tell CtrlP not to split when opening a file from NERDTree
let g:ctrlp_dont_split = 'NERD'

" Ensure CtrlP opens file in a writeable buffer (not NERDTree)
" https://vi.stackexchange.com/questions/10016/stop-ctrlp-from-opening-in-nerdtree

function! CtrlPCommand()
    let c = 0
    let wincount = winnr('$')
    " Don't open it here if current buffer is not writable (e.g. NERDTree)
    while !empty(getbufvar(+expand("<abuf>"), "&buftype")) && c < wincount
        exec 'wincmd w'
        let c = c + 1
    endwhile
    exec 'CtrlP'
endfunction

let g:ctrlp_cmd = 'call CtrlPCommand()'

" ### vim-prettier

" Enable vim-prettier to run (async) in files without requiring the "@format" doc tag
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync

" ### NERDTree
" TODO: Pursue setup here https://medium.com/@victormours/a-better-nerdtree-setup-3d3921abc0b9

" Open NERDTree when vim starts up (unless entering a git commit or todo.txt)
" https://vi.stackexchange.com/questions/15997/change-buffer-focus-on-enter
let file_name = expand('%:t')
:autocmd VimEnter * if (&filetype !=# 'gitcommit') && (file_name !=# 'todo.txt') && (file_name !=# 'git-rebase-todo') && (file_name !=# 'PULLREQ_EDITMSG') | NERDTree | wincmd w | endif

" https://codeyarns.com/2014/05/05/how-to-highlight-current-file-in-nerdtree/

" Check if NERDTree is open or active
function! s:isNERDTreeOpen()
  return exists("t:NERDTreeBufName") && (bufwinnr(t:NERDTreeBufName) != -1)
endfunction

" Call NERDTreeFind iff NERDTree is active, current window contains a modifiable
" file, and we're not in vimdiff
function! s:syncTree()
  if &modifiable && s:isNERDTreeOpen() && strlen(expand('%')) > 0 && !&diff
    NERDTreeFind
    wincmd p
  endif
endfunction

" Highlight currently open buffer in NERDTree
autocmd BufEnter * call s:syncTree()

" ### Ale

" Recommended configuration for linting / fixing
" https://www.vimfromscratch.com/articles/setting-up-vim-for-typescript/
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'typescript': ['tsserver', 'tslint']
\}
let g:ale_fixers = {
\    'javascript': ['eslint'],
\    'typescript': ['prettier'],
\    'html': ['prettier']
\}
let g:ale_fix_on_save = 1
