echo "Loading zsh configuration"
echo "..."

# Path to your oh-my-zsh installation.
export ZSH=/Users/$USER/.oh-my-zsh
export DOTFILES_PATH="$HOME/git/me/bag-of-tricks"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="simple"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh
source $DOTFILES_PATH/rc/todo.cfg

# Custom zsh configuration

alias gcur='echo $(git_current_branch)'
alias todo='todo.sh'
alias vtodo='vim $TODO_FILE'

# Base vi mode configuration
# https://dougblack.io/words/zsh-vi-mode.html

bindkey -v

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# Override cursor behavior to detect mode
# http://lynnard.me/blog/2014/01/05/change-cursor-shape-for-zsh-vi-mode/

function zle-keymap-select {
    if [ "$TERM" = "xterm-256color" ]; then
        if [ $KEYMAP = vicmd ]; then
            # the command mode for vi
            echo -ne "\e[2 q"
        else
            # the insert mode for vi
            echo -ne "\e[4 q"
        fi
    fi
}

zle -N zle-keymap-select
export KEYTIMEOUT=1

# Bash configuration

source ~/.bashrc

echo "Successfully loaded zsh configuration"
echo "..."
